### PR TITLE
added fetch command for edamam

### LINKED ISSUE #24: JS-Fetch data from Edamame API for
Use the Edamame API to get a recipe to go with your pairing.

### PR DESCRIPTION
**Pull request by ghost**
I left the command open ended as I do not know whether a search bar or dropdown menu is intended. Therefore it is designed to pull generally from the API

### CODE REVIEW

**Review by ElodieLongo — COMMENTED** [review]
Gwen and I are still in meeting and checking this.

Could you please move lines 50 to 61 to the file named: recipe-generator.js

**Comment by ghost** [comment]
Is it okay to have multiple JS files? You would have to run that by the instructor.

**Comment by ghost** [comment]
Content has been moved to JS file of choice. I will reach out to the instructor with additional comment.

**Comment by ghost** [comment]
Please see new pull request for my information in my files

**Pull request closed without merging**
